title: Air Quality Dashboard
description: Forecast & hindcast for multiple sensors
# For project pages (username.github.io/repo-name)
# If this is a user/organization site, set baseurl: "" instead
baseurl: "/air-quality-prediction"
url: "https://cimun.github.io"

theme: minima  # optional; you can remove this if you don't want theme styles

# Prevent Jekyll from ignoring assets in docs/air-quality
include:
  - air-quality
